# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac1b6cd0893c879649841e3ef203b69fb40bc4f269e54f08de7cb12ed1ded2ddded7a2424a123e8b381104fca94a5d3283b7c020b284dbf9016d08da41eed5ad

test:
  secret_key_base: 95e2a6c58a2b7c7f4be11f47985cf8c6d8fc44afa4129e5c92811502a9199a0b62c883800475df0fdfddf5d3c59b2db3580be61c64ae181eb911e89d329118fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
